export const INITIAL_STATE = {
  cos: 1,
};

export enum ACTIONS {
  SEARCH_START = "SEARCH_START",
  SEARCH_SUCCESS = "SEARCH_SUCCESS",
  SEARCH_ERROR = "SEARCH_ERROR",
  SEARCH_CLEAR = "SEARCH_CLEAR",
}
